stages:
  get_data:
    cmd: python3 src/get_data.py
    deps:
      - src/get_data.py
    params:
      - get_data.output_path
    outs:
      - ${get_data.output_path}:
          persist: true
  cleaning:
    cmd: python3 src/cleaning.py
    deps:
      - src/cleaning.py
      - ${cleaning.input_path}
    params:
      - cleaning.output_path
      - cleaning.input_path
    outs:
      - ${cleaning.output_path}:
          persist: true
  aggregate_tracks:
    cmd: python3 src/aggregate_tracks.py
    deps:
      - src/aggregate_tracks.py
      - ${aggregate_tracks.input_path}
    params:
      - aggregate_tracks.output_path
      - aggregate_tracks.input_path
    outs:
      - ${aggregate_tracks.output_path}:
          persist: true
  merge_datasets:
    cmd: python3 src/merge_datasets.py
    deps:
      - src/merge_datasets.py
      - ${merge_datasets.input_path.tracks}
      - ${merge_datasets.input_path.train_flight_list}
      - ${merge_datasets.input_path.test_flight_list}
    params:
      - merge_datasets.output_path
      - merge_datasets.input_path.tracks
      - merge_datasets.input_path.train_flight_list
      - merge_datasets.input_path.test_flight_list
    outs:
      - ${merge_datasets.output_path.train}:
          persist: true
      - ${merge_datasets.output_path.test}:
          persist: true
  split_data:
    cmd: python3 src/split_data.py
    deps:
      - src/split_data.py
      - ${split_data.input_path}
    params:
      - split_data.output_path
      - split_data.input_path
      - all.dtypes
      - all.random_state
      - all.target
    outs:
      - ${split_data.output_path.train}:
          persist: true
      - ${split_data.output_path.val}:
          persist: true
  feature_selection:
    cmd: python3 src/feature_selection.py
    deps:
      - src/feature_selection.py
      - ${feature_selection.input_path}
    params:
      - feature_selection.output_path
      - feature_selection.input_path
      - feature_selection.fs_validation_frac
      - all.random_state
      - all.dtypes
      - all.categorical_features
      - all.target
    outs:
      - ${feature_selection.output_path}:
          persist: true
          cache: false
  baseline_model:
    cmd: python3 src/baseline_model.py
    deps:
      - src/baseline_model.py
      - ${baseline_model.input_path}
    params:
      - baseline_model.output_path
      - baseline_model.input_path
      - baseline_model.baseline_validation_frac
      - all.random_state
      - all.dtypes
      - all.categorical_features
      - all.target
    outs:
      - ${baseline_model.output_path}:
          persist: true

  train_catboost:
    cmd: python3 src/train_catboost.py
    deps:
      - src/train_catboost.py
      - ${train_catboost.input_path.train_data}
      - ${train_catboost.input_path.validation_data}
      - ${train_catboost.input_path.selected_features}
    params:
      - train_catboost.output_path
      - train_catboost.input_path.train_data
      - train_catboost.input_path.validation_data
      - train_catboost.params_grid
      - train_catboost.early_stopping_rounds
      - train_catboost.cv_folds
      - train_catboost.random_search_iters
      - all.dtypes
      - all.categorical_features
      - all.target
      - all.random_state
    outs:
      - ${train_catboost.output_path}:
          persist: true

  predict_submission:
    cmd: python3 src/predict_submission.py
    deps:
      - src/predict_submission.py
      - ${predict_submission.input_path.data}
      - ${predict_submission.input_path.model}
    params:
      - predict_submission.output_path
      - predict_submission.input_path.data
      - predict_submission.input_path.model
    outs:
      - ${predict_submission.output_path}:
          persist: true
