get_data:
  output_path: data/raw
cleaning:
  output_path: data/interim/clean_tracks
  input_path: data/raw
  timedelta_threshold: 10  # in minutes
  restart: False
aggregate_tracks:
  input_path: data/interim/clean_tracks
  output_path: data/interim/aggregate_tracks
  restart: True